### ISSUE TITLE
extract hand data from data read in from the kinect

### ISSUE THREAD

**Issue by mloo3** [cclaassen3/augmented_climbing#17]

**Comment by cclaassen3** [comment]
modified this to read in all body data instead of only hand data.

this was because the library did not support skeletal tracking for the kinect v1, so instead of getting the skeletal data directly from the kinect, I use the video stream to do image processing (background subtraction on all color channels, combining them, thresholding, dilating, eroding) such that the output is an image where the pixels representing the climber should be white (e.g. 255,255,255) and the rest should be black (e.g. 0,0,0)
